### ISSUE TITLE
Typo in repository name

### ISSUE THREAD

**Issue by junkangli** [aws-samples/vpn-gateway-strongswan#20]
This repository is named `vpn-gateway-strongwswan` (note the extra _w_ between _strong_ and _swan_), which makes use of **strongSwan**. So, should it be named `vpn-gateway-strongswan` instead?

**Comment by ckamps** [comment]
You are correct.  While we publish a second blog post addressing configuration of certificate-based authentication, I'll fix the repository name and update the first blog post.  This should occur in the next few weeks.

**Comment by ckamps** [comment]
@junkangli - FYI - I just renamed the repo to remove the extra "w". The associated blog posts' references to the repo are also in the process of being updated. Thanks for filing this issue!
